### ISSUE TITLE
Unable to setup since upgrading to v 2.0.1

### ISSUE THREAD

**Issue by n00bcodr** [amosyuen/ha-tplink-deco#49]
## Version of the custom_component

v 2.0.1

## Configuration

```
n/a?
```

## Describe the bug

![image](https://user-images.githubusercontent.com/49611451/157042648-9f3b3a43-0d6e-47b2-92da-de09b05dbf64.png)

## Debug log

```2022-03-07 18:51:28 ERROR (MainThread) [custom_components.tplink_deco] Unexpected error fetching tplink_deco-decos data: 'hardware_ver'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 169, in _async_update_data
    deco.update(new_deco)
  File "/config/custom_components/tplink_deco/coordinator.py", line 71, in update
    self.hw_version = data["hardware_ver"]
KeyError: 'hardware_ver'


```

**Comment by pex81** [comment]
i have a similar problem after 2.0.1 update

```
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/coordinator.py:78 
Integration: TP-Link Deco ([documentation](https://github.com/amosyuen/ha-tplink-deco), [issues](https://github.com/amosyuen/ha-tplink-deco/issues)) 
First occurred: 17:32:36 (6 occurrences) 
Last logged: 17:36:22

Unexpected error fetching tplink_deco-decos data: 'device_ip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 169, in _async_update_data
    deco.update(new_deco)
  File "/config/custom_components/tplink_deco/coordinator.py", line 78, in update
    self.ip_address = filter_invalid_ip(data["device_ip"])
KeyError: 'device_ip'
```

**Comment by Pawel128** [comment]
v.2.0.1  retrying setup
--------
the same for two installations
--------
core-2022.3.2
supervisor-2022.01.1
Home Assistant OS 7.4
-----------------------------------
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/coordinator.py:78
Integration: TP-Link Deco (documentation, issues)
First occurred: 20:04:36 (23 occurrences)
Last logged: 20:30:22

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:57
Integration: TP-Link Deco (documentation, issues)
First occurred: 20:17:11 (1 occurrences)
Last logged: 20:17:11

Error testing credentials: 'device_ip'
--------------------------------
Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:309
Integration: TP-Link Deco (documentation, issues)
First occurred: 20:17:08 (1 occurrences)
Last logged: 20:17:08

Unexpected error fetching tplink_deco-decos data:
Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/api.py", line 278, in _async_post
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.68.1/cgi-bin/luci/;stok=/login?form=login')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/coordinator.py", line 39, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 122, in async_list_devices
    await self.async_login()
  File "/config/custom_components/tplink_deco/api.py", line 236, in async_login
    response_json = await self._async_post(
  File "/config/custom_components/tplink_deco/api.py", line 309, in _async_post
    raise AuthException from err
custom_components.tplink_deco.exceptions.AuthException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/api.py", line 278, in _async_post
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.xxx.xxx/cgi-bin/luci/;stok=fa3104b16665f7d66c4483127311fe3b/admin/device?form=device_list')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 158, in _async_update_data
    new_decos = await async_call_with_retry(self._api.async_list_devices)
  File "/config/custom_components/tplink_deco/coordinator.py", line 42, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 126, in async_list_devices
    response_json = await self._async_post(
  File "/config/custom_components/tplink_deco/api.py", line 309, in _async_post
    raise AuthException from err
custom_components.tplink_deco.exceptions.AuthException

-------------------------------
Unexpected error fetching tplink_deco-decos data: 'device_ip'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 169, in _async_update_data
    deco.update(new_deco)
  File "/config/custom_components/tplink_deco/coordinator.py", line 78, in update
    self.ip_address = filter_invalid_ip(data["device_ip"])
KeyError: 'device_ip'

**Comment by amosyuen** [comment]
What version of decos do you have? Seems that maybe not all decos have that field

**Comment by mac-n-cheese-uk** [comment]
I've got Deco P9's and an M3W and getting the following:

```
  File "/config/custom_components/tplink_deco/coordinator.py", line 169, in _async_update_data
    deco.update(new_deco)
  File "/config/custom_components/tplink_deco/coordinator.py", line 71, in update
    self.hw_version = data["hardware_ver"]
KeyError: 'hardware_ver'
```

**Comment by Pawel128** [comment]
Deco P7

**Comment by rogersau** [comment]
> What's strange is, I am trying to setup by installing an older version, I am still getting the same error.

I had the same issue, i removed the integration and redownloaded version 1.1.1

**Comment by n00bcodr** [comment]
> What version of decos do you have? Seems that maybe not all decos have that field

3 x M5
2 x X60
1 x M3W

**Comment by n00bcodr** [comment]
> > What's strange is, I am trying to setup by installing an older version, I am still getting the same error.
> 
> I had the same issue, i removed the integration and redownloaded version 1.1.1

Did that work? @rogersau

**Comment by Pawel128** [comment]
@n00bcodr yes, it works for me.

**Comment by mousawm** [comment]
Hi,

I'm also just got the same error:

````text
This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:334
Integration: TP-Link Deco (documentation, issues)
First occurred: 11:09:19 AM (160 occurrences)
Last logged: 11:48:53 AM

Unexpected error fetching tplink_deco-decos data: unsupported operand type(s) for +: 'NoneType' and 'int'
Unexpected error fetching tplink_deco-clients data: unsupported operand type(s) for +: 'NoneType' and 'int'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 158, in _async_update_data
    new_decos = await async_call_with_retry(self._api.async_list_devices)
  File "/config/custom_components/tplink_deco/coordinator.py", line 39, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 130, in async_list_devices
    data=self._encode_payload(device_list_payload),
  File "/config/custom_components/tplink_deco/api.py", line 328, in _encode_payload
    sign = self._encode_sign(len(data))
  File "/config/custom_components/tplink_deco/api.py", line 334, in _encode_sign
    seq_with_data_len = self._seq + data_len
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
````

and the devices status become unavailable.

**Comment by n00bcodr** [comment]
Not working for me :(

I removed it, re-downloaded 1.1.1, rebooted my host. I have the same issue. 😢 

![image](https://user-images.githubusercontent.com/49611451/157205273-a00b3a04-e36f-4697-b20c-05be8844e763.png)


```2022-03-08 14:40:24 ERROR (MainThread) [custom_components.tplink_deco] Unexpected error fetching tplink_deco-decos data: 'hardware_ver'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 169, in _async_update_data
    deco.update(new_deco)
  File "/config/custom_components/tplink_deco/coordinator.py", line 71, in update
    self.hw_version = data["hardware_ver"]
KeyError: 'hardware_ver'
2022-03-08 14:40:24 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-decos data in 4.769 seconds (success: False)
2022-03-08 14:40:24 WARNING (MainThread) [custom_components.tplink_deco] Error testing credentials: 'hardware_ver'
E0308 14:40:53.947541891     218 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies```

**Comment by amosyuen** [comment]
> Not working for me :(
> 
> I removed it, re-downloaded 1.1.1, rebooted my host. I have the same issue. 😢
> 
> ![image](https://user-images.githubusercontent.com/49611451/157205273-a00b3a04-e36f-4697-b20c-05be8844e763.png)
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
>     self.data = await self._async_update_data()
>   File "/config/custom_components/tplink_deco/coordinator.py", line 169, in _async_update_data
>     deco.update(new_deco)
>   File "/config/custom_components/tplink_deco/coordinator.py", line 71, in update
>     self.hw_version = data["hardware_ver"]
> KeyError: 'hardware_ver'
> 2022-03-08 14:40:24 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-decos data in 4.769 seconds (success: False)
> 2022-03-08 14:40:24 WARNING (MainThread) [custom_components.tplink_deco] Error testing credentials: 'hardware_ver'
> E0308 14:40:53.947541891     218 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies```
> ```

Most likely it didn't actually properly download v1.0.1 as the code referenced is from v2.0.1. Sometimes HACS does this, I found for me make sure after you select the version in the dropdown box, it becomes disabled for a short while, make sure you wait till it becomes enabled again before clicking "Download" button.

I've released [v2.0.2](https://github.com/amosyuen/ha-tplink-deco/releases/tag/v2.0.2), which should handle the missing properties. I've also added debug logging to log the responses of the list devices (decos) and list clients calls. If you could enable debug logging and send me the logged reponses it would be useful to see what properties the decos have for your deco models.

**Comment by n00bcodr** [comment]
2.0.2 is working perfectly for me, with the changes intended in 2.0.1.

Would you still need logs?

**Comment by amosyuen** [comment]
That's great that it's working, yes, please still send logs.

The problem earlier was that the decos returned didn't have a field such as "hardware_ver", so with the latest fix it is just set to `None`. However, it's possible the data is in the response but with a different key. By sending me the logs I can check whether this is because the field has a different key or if there is other useful info in other deco models to expose.

**Comment by Afterdark1st** [comment]
Hi I am still getting this error with v2.0.1 or v2.0.2? configuration is successful 
2022-03-09 10:51:34 ERROR (MainThread) [custom_components.tplink_deco] Fetch keys client error: Cannot connect to host none:80 ssl:default [Try again]
2022-03-09 10:51:36 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready(

<img width="203" alt="Capture" src="https://user-images.githubusercontent.com/55333417/157430522-192c1469-3b89-45aa-9901-256848e9afc1.PNG">

**Comment by amosyuen** [comment]
> Hi I am still getting this error with v2.0.1 or v2.0.2? configuration is successful 2022-03-09 10:51:34 ERROR (MainThread) [custom_components.tplink_deco] Fetch keys client error: Cannot connect to host none:80 ssl:default [Try again] 2022-03-09 10:51:36 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready(
> 
> <img alt="Capture" width="203" src="https://user-images.githubusercontent.com/55333417/157430522-192c1469-3b89-45aa-9901-256848e9afc1.PNG">

That error seems to indicate that the host field is none or empty, could you confirm that the host field in the config has a value set? Do you get this error if you completely remove and re-add the integration?

**Comment by Afterdark1st** [comment]
Hi thx for the suggestion a delete and reinstall did work on the 3rd try all working fine now

**Comment by sambarlick** [comment]
Hi, I am new to this integration and i can't set it up.
The integration won't connect to my Decos. I have 3x M4. I set up an secondary user as the instructions suggest for me to use for the app and I am trying to login with the original/owner password.

![Screenshot_20220310-150756](https://user-images.githubusercontent.com/47462284/157588771-d7744afe-5bd3-492a-8612-0d1481073a4e.png)

**Comment by amosyuen** [comment]
Please enable debug logging and send the logs you see

**Comment by sambarlick** [comment]
2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-EB-68-B0 timed out
2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-clients data in 60.029 seconds (success: False)
2022-03-10 16:17:31 WARNING (MainThread) [custom_components.tplink_deco] Error testing credentials: 
2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-BE-53-3C timed out
2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-BE-53-18 timed out

This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/config_flow.py:57
Integration: tplink_deco (documentation, issues)
First occurred: 4:13:53 PM (2 occurrences)
Last logged: 4:17:31 PM

Error testing credentials: Invalid login credentials. 8 attempts remaining.
Error testing credentials:

**Comment by sambarlick** [comment]
I used this in my config.yaml. 

logger:
  default: info
  logs:
    custom_components.tplink_deco: debug

I hope its correct I've never got debug logs before.

**Comment by sambarlick** [comment]
> 2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-EB-68-B0 timed out
> 2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-BE-53-3C timed out
> 2022-03-10 16:17:31 DEBUG (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-BE-53-18 timed out

These MAC addresses are my Decos, if it can't log in can it still get the MACs?

**Comment by sambarlick** [comment]
More logs... But I think this was when I entered my password incorrectly.

This error originated from a custom integration.

Logger: custom_components.tplink_deco
Source: custom_components/tplink_deco/api.py:250
Integration: TP-Link Deco (documentation, issues)
First occurred: 4:50:11 PM (1 occurrences)
Last logged: 4:50:11 PM

Unexpected error fetching tplink_deco-decos data: Invalid login credentials. 8 attempts remaining.
Traceback (most recent call last):
  File "/config/custom_components/tplink_deco/coordinator.py", line 39, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 122, in async_list_devices
    await self.async_login()
  File "/config/custom_components/tplink_deco/api.py", line 250, in async_login
    raise AuthException(
custom_components.tplink_deco.exceptions.AuthException: Invalid login credentials. 9 attempts remaining.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tplink_deco/coordinator.py", line 159, in _async_update_data
    new_decos = await async_call_with_retry(self._api.async_list_devices)
  File "/config/custom_components/tplink_deco/coordinator.py", line 42, in async_call_with_retry
    return await func(*args)
  File "/config/custom_components/tplink_deco/api.py", line 122, in async_list_devices
    await self.async_login()
  File "/config/custom_components/tplink_deco/api.py", line 250, in async_login
    raise AuthException(
custom_components.tplink_deco.exceptions.AuthException: Invalid login credentials. 8 attempts remaining.

**Comment by amosyuen** [comment]
That's interesting, since it got the MACs looks like the list decos worked, but for some reason the list clients call times out. Was it able to add any device_trackers for you besides the ones for the decos? Curious what Deco model you have?

**Comment by sambarlick** [comment]
The integration fails to set up. I get the error message in this screenshot.
![Screenshot_20220310-150756](https://user-images.githubusercontent.com/47462284/157604486-7c06a968-9f03-48a6-892d-d6cb8f94cc1b.png)
I have 3x M4.

**Comment by sambarlick** [comment]
If it helps my Deco M4 s are on 1.5.4 Build 20220113 Rel. 38349

**Comment by sambarlick** [comment]
More logs

2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] aes_key=6236535621622916
2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] aes_iv=7903946538840756
2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] password_rsa_n=147400152213047990727033136147004346733103031985288458332450458806859242043605003404150174090446171651650480460233560027136327325663456109096372971869531130727197464059178168406922984183008755410378326074461124456947748570215827915280709053787014995116751665099191965014918961216467473409603919228363587361789
2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] password_rsa_e=65537
2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] sign_rsa_n=12037157877008191069986003012329839435415431264373572226977717299080492312645307743587690758248055189194037318757997907876796126383805410623003499893176231
2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] sign_rsa_e=65537
2022-03-10 18:55:42 DEBUG (MainThread) [custom_components.tplink_deco] seq=834174909
2022-03-10 18:55:45 DEBUG (MainThread) [custom_components.tplink_deco] cookie=sysauth=66f1d4bf6cce406e7b2a37cfd75e6e26
2022-03-10 18:55:45 DEBUG (MainThread) [custom_components.tplink_deco] stok=0b3cf544437b4fa0d5986cd787f492c2

**Comment by amosyuen** [comment]
At least one other user has reported having success with M4 Decos.

* Could you confirm if your decos are on the latest firmware?
* If you login to the deco webportal with the account credentials, are you able to view the list of clients alright? Does it take a long time?

**Comment by sambarlick** [comment]
> At least one other user has reported having success with M4 Decos.
> 
> * Could you confirm if your decos are on the latest firmware?

Yes, I can confirm latest firmware. There was an update a couple of days ago.

> * If you login to the deco webportal with the account credentials, are you able to view the list of clients alright? Does it take a long time?

Yes I can see the list, sometimes it takes a minute or two other times it loads fine.

From the last set of logs it seems that the integration does login as it gets a lot of information. Are you thinking this is a time out issue?

**Comment by Pawel128** [comment]
@sambarlick sorry if you know this but: is your main Deco ip 192.168.8.1 for sure?

**Comment by amosyuen** [comment]
> > At least one other user has reported having success with M4 Decos.
> > 
> > * Could you confirm if your decos are on the latest firmware?
> 
> Yes, I can confirm latest firmware. There was an update a couple of days ago.
> 
> > * If you login to the deco webportal with the account credentials, are you able to view the list of clients alright? Does it take a long time?
> 
> Yes I can see the list, sometimes it takes a minute or two other times it loads fine.
> 
> From the last set of logs it seems that the integration does login as it gets a lot of information. Are you thinking this is a time out issue?

The errors indicate that the list clients calls are timing out in 60s. If you look in the browser developer console network info, can you see how long the list clients call is taking when signed into the UI? If it is taking longer than 60s then, maybe we just need a longer timeout.

**Comment by sambarlick** [comment]
> > > At least one other user has reported having success with M4 Decos.
> > > 
> > > * Could you confirm if your decos are on the latest firmware?
> > 
> > 
> > Yes, I can confirm latest firmware. There was an update a couple of days ago.
> > > * If you login to the deco webportal with the account credentials, are you able to view the list of clients alright? Does it take a long time?
> > 
> > 
> > Yes I can see the list, sometimes it takes a minute or two other times it loads fine.
> > From the last set of logs it seems that the integration does login as it gets a lot of information. Are you thinking this is a time out issue?
> 
> The errors indicate that the list clients calls are timing out in 60s. If you look in the browser developer console network info, can you see how long the list clients call is taking when signed into the UI? If it is taking longer than 60s then, maybe we just need a longer timeout.

I'm sorry for the delay,

The client list doesn't load. The console indicates that it keeps timing out at 15s and repeats the process timing out at 15s.
The client list loads in the app, not sure why it doesn't in a browser.

> I can confirm M4 Deco's work fine if you enter the credentials wrong (as i did) you just need to delete the integration/remove the integration reboot then reinstall and all should be ok from there

I thought of that but I have entered my password correctly after a fresh install and in still doesn't work.

**Comment by amosyuen** [comment]
Hmm, that's interesting. Well can you try changing your local file in your custom_components, set the `TIMEOUT` variable https://github.com/amosyuen/ha-tplink-deco/blob/master/custom_components/tplink_deco/api.py#L26 to some large value like 300 (5 minutes) and see if that helps.

**Comment by sambarlick** [comment]
> Hmm, that's interesting. Well can you try changing your local file in your custom_components, set the `TIMEOUT` variable https://github.com/amosyuen/ha-tplink-deco/blob/master/custom_components/tplink_deco/api.py#L26 to some large value like 300 (5 minutes) and see if that helps.

That did it! Thanks.

**Comment by n00bcodr** [comment]
@amosyuen should I close this?

**Comment by amosyuen** [comment]
@sambarlick Could you let me know based on debug logs what is the approximate time it took for it to update the client list (not deco list)? I can update the TIMEOUT to be larger than that.

I think we can close out this issue after I make that update.

**Comment by sambarlick** [comment]
I'm now getting a new error!! I haven't changed anything.

Error testing credentials: 502, message='Bad Gateway', url=URL('http://192.168.8.1/cgi-bin/luci/;stok=bd42701062837b4fa94eaa70cbe14482/admin/client?form=client_list')
List Clients 1C-3B-F3-BE-53-18 client response error: 502, message='Bad Gateway', url=URL('http://192.168.8.1/cgi-bin/luci/;stok=bd42701062837b4fa94eaa70cbe14482/admin/client?form=client_list')
List Clients 1C-3B-F3-EB-68-B0 client response error: 502, message='Bad Gateway', url=URL('http://192.168.8.1/cgi-bin/luci/;stok=bd42701062837b4fa94eaa70cbe14482/admin/client?form=client_list')

**Comment by sambarlick** [comment]
2022-03-14 12:46:50 ERROR (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-BE-53-18 client response error: 502, message='Bad Gateway', url=URL('http://192.168.8.1/cgi-bin/luci/;stok=5118e77f8e7949d2d8b79924d44b33a0/admin/client?form=client_list')
2022-03-14 12:46:50 DEBUG (MainThread) [custom_components.tplink_deco] Finished fetching tplink_deco-clients data in 60.097 seconds (success: False)
2022-03-14 12:46:50 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.8.1' for tplink_deco integration not ready yet: 502, message='Bad Gateway', url=URL('http://192.168.8.1/cgi-bin/luci/;stok=5118e77f8e7949d2d8b79924d44b33a0/admin/client?form=client_list'); Retrying in background
2022-03-14 12:46:50 ERROR (MainThread) [custom_components.tplink_deco] List Clients 1C-3B-F3-BE-53-3C client response error: 502, message='Bad Gateway', url=URL('http://192.168.8.1/cgi-bin/luci/;stok=5118e77f8e7949d2d8b79924d44b33a0/admin/client?form=client_list')

**Comment by amosyuen** [comment]
Looks like the timeout didn't really do anything then. At this point seems the integration is working fine, just that there's some problem with your deco unit since the web portal isn't even working. You can try some general stuff like rebooting or resetting your deco to see if that helps. But as long as your web portal isn't working there isn't much I can do.

At this point going to close this issue then.

**Comment by sambarlick** [comment]
Ok, thanks for all your help.
